### ISSUE TITLE
Failed to load required native library 'C:\windows\Microsoft.NET\Framework64\v4.0.30319\wminet_utils.dll'

### ISSUE THREAD

**Issue by LinAGKar** [neatodev/BmLauncherAsylumNET6#6]
I'm trying to run the standalone version in Proton, and I've installed all the protontricks dependencies in accordance with the readme, but I'm getting an error:

```
2023-04-16 13:48:28.2589|INFO|BmLauncherAsylumNET6.Program|Main - Starting logs at 13:48:28, on 16 April 2023.
2023-04-16 13:48:28.2755|DEBUG|BmLauncherAsylumNET6.Program|getResolutions - found a total of 22 available resolutions.
2023-04-16 13:48:28.6132|INFO|BmLauncherAsylumNET6.infrastructure.Factory|Constructor - Created Factory
Unhandled exception. System.TypeInitializationException: The type initializer for 'System.Management.WmiNetUtilsHelper' threw an exception.
 ---> System.ComponentModel.Win32Exception (126): Failed to load required native library 'C:\windows\Microsoft.NET\Framework64\v4.0.30319\wminet_utils.dll'.
   at System.Management.WmiNetUtilsHelper..cctor()
   --- End of inner exception stack trace ---
   at System.Management.ThreadDispatch.Start()
   at System.Management.ManagementScope.Initialize()
   at System.Management.ManagementObjectSearcher.Initialize()
   at System.Management.ManagementObjectSearcher.Get()
   at BmLauncherAsylumNET6.infrastructure.Factory.setGPUname()
   at BmLauncherAsylumNET6.infrastructure.Factory..ctor(BmLauncherForm form)
   at BmLauncherAsylumNET6.Program.RunWindow()
   at BmLauncherAsylumNET6.Program.Main()
ThreadGetProcessExitCode: no such process 14001
ThreadGetProcessExitCode: no such process 13983
ThreadGetProcessExitCode: no such process 13970
ThreadGetProcessExitCode: no such process 13959
ThreadGetProcessExitCode: no such process 13950
ThreadGetProcessExitCode: no such process 13894
ThreadGetProcessExitCode: no such process 13888
ThreadGetProcessExitCode: no such process 13866
pid 13878 != 13877, skipping destruction (fork without exec?)
Game process removed: AppID 35140 "/home/linus/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=35140 -- /home/linus/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/home/linus/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/home/linus/.local/share/Steam/steamapps/common/Proton - Experimental'/proton waitforexitandrun  '/home/linus/.local/share/Steam/steamapps/common/Batman Arkham Asylum GOTY/Binaries/BmLauncher.exe'", ProcID 13876
```

Operating System: openSUSE Tumbleweed 20230414
KDE Plasma Version: 5.27.4
KDE Frameworks Version: 5.105.0
Qt Version: 5.15.8
Kernel Version: 6.2.10-1-default (64-bit)
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 5800X 8-Core Processor
Memory: 62.7 Gibyte of RAM
Graphics Processor: NVIDIA GeForce RTX 2080 Ti/PCIe/SSE2
Manufacturer: ASUS

**Comment by InfiniteLoopGameDev** [comment]
Hey, I originally had the same problem but I installed dotnet40 and it successfully ran

**Comment by Arbitrate3280** [comment]
Same issue on fedora 39. I installed dotnet40 using winetricks but it's showing me this:

"Unhandled exception. System.PlatformNotSupportedException: The native library 'C:\windows\Microsoft.NET\Framework64\v4.0.30319\wminet_utils.dll' does not have all required functions. Please, update the .NET Framework:
